#!/usr/bin/env python3
"""Build js/custom-art/map.js from the deluxe list + researched art (custom_art.json).

custom_art.json format: [{"title": "Song Title", "file": "celeste.jpg", "artist": "d4vd"}, ...]
Images must already exist in js/custom-art/. Values are {s: src, a: artist-key};
the app only enforces the artist when the track has a real artist tag.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARTDIR = os.path.join(HERE, 'js', 'custom-art')
MAPJS = os.path.join(ARTDIR, 'map.js')
JSON = os.path.join(HERE, 'custom_art.json')

DELUXE = [
    "Favorite",
    "Issues",
    "Take the Photos (featuring Malcolm Todd)",
    "How Do You Sleep?",
    "You Still Love Me",
    "Best Friend (featuring RealestK)",
    "I'm Good",
    "Always Love (with Hyunjin)",
    "11PM",
    "Summer Don't End (featuring Keshi)",
    "Talking to Myself",
    "Affirmation",
    "L.O.V.E.U (featuring Hannah Bahng)",
    "Glue (featuring Julia Wolf)",
    "Frontline",
]

def norm(s):
    return re.sub(r'[^a-z0-9]', '', (s or '').lower())

def norm_base(s):
    return norm(re.sub(r'\s*[\(\[].*?[\)\]]', '', s or ''))

entries = {}
for t in DELUXE:
    for k in {norm(t), norm_base(t)}:
        if k:
            entries[k] = ('js/custom-art/marcescence.jpg', 'd4vd')

extra = []
if os.path.exists(JSON):
    extra = json.load(open(JSON))
for item in extra:
    f = item['file']
    if not os.path.exists(os.path.join(ARTDIR, f)):
        print(f'WARN: missing image {f} for "{item["title"]}", skipped', file=sys.stderr)
        continue
    akey = norm(item.get('artist', ''))
    for k in {norm(item['title']), norm_base(item['title'])}:
        if k and k not in entries:
            entries[k] = (f'js/custom-art/{f}', akey)

lines = ['/* Curated cover-art overrides. Generated by build-custom-art.py — do not hand-edit. */',
         'window.CUSTOM_ART = {};']
for k in sorted(entries):
    s, a = entries[k]
    lines.append(f'window.CUSTOM_ART[{k!r}] = {{s:{s!r},a:{a!r}}};')
lines.append(f'/* {len(entries)} title keys */')
open(MAPJS, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {MAPJS}: {len(entries)} keys, {len(extra)} researched songs')

# Curated metadata fixes: custom_meta.json -> js/custom-art/meta.js
# Format: [{"match": {"artist": "...", "title": "..."}, "fix": {"artist": "...", "title": "..."}}]
# Match keys are lowercased+trimmed; fix values are applied verbatim.
METAJ = os.path.join(HERE, 'custom_meta.json')
METJS = os.path.join(ARTDIR, 'meta.js')
mitems = json.load(open(METAJ)) if os.path.exists(METAJ) else []
mlines = ['/* Curated metadata fixes. Generated by build-custom-art.py — do not hand-edit. */',
          'window.CUSTOM_META = [];']
for it in mitems:
    m, f = it.get('match', {}), it.get('fix', {})
    ma, mt = (m.get('artist') or '').strip().lower(), (m.get('title') or '').strip().lower()
    fa, ft = f.get('artist'), f.get('title')
    if not (ma and mt and (fa or ft)):
        print(f'WARN: bad meta entry skipped: {it}', file=sys.stderr)
        continue
    mlines.append(f'window.CUSTOM_META.push({{a:{ma!r},t:{mt!r},fa:{fa!r},ft:{ft!r}}});')
mlines.append(f'/* {len(mitems)} metadata fixes */')
open(METJS, 'w').write('\n'.join(mlines) + '\n')
print(f'wrote {METJS}: {len(mitems)} fixes')
