/* Curated metadata fixes. Generated by build-custom-art.py — do not hand-edit. */
window.CUSTOM_META = [];
window.CUSTOM_META.push({a:'celeste (demo',t:'unfinished)',fa:'d4vd',ft:'Celeste'});
/* 1 metadata fixes */
